### ISSUE TITLE
Error: "digital envelope routines::unsupported" with Node.js v18.12.0

### ISSUE THREAD

**Issue by danikishin** [OPCODES-GITHUB/dasaka-UI#2]
Hello!

I ran into a problem while trying to run the Dasaka-UI project using Node.js v18.12.0. Specifically, when I tried to run npm run dev, I got the following error message:

"ERROR Error: error:0308010C:digital envelope routines::unsupported
...
Error: error:0308010C:digital envelope routines::unsupported
at new Hash (node:internal/crypto/hash:71:19)
at Object.createHash (node:crypto:133:10)
...
opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
library: 'digital envelope routines',
reason: 'unsupported',
code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
Node.js v18.12.0"

It looks like this issue might be related to the crypto module in Node.js. Unfortunately, this error is preventing me from running the project using the latest version of Node.js. I was wondering if there are any plans to update the project to support newer Node.js versions, or if there might be a workaround that doesn't involve downgrading Node.js?

**Comment by danikishin** [comment]
Tried with docker, same error.

Error: error:0308010C:digital envelope routines::unsupported
dasaka-ui  |     at new Hash (node:internal/crypto/hash:71:19)
dasaka-ui  |     at Object.createHash (node:crypto:133:10)
dasaka-ui  |     at module.exports (/app/node_modules/webpack/lib/util/createHash.js:135:53)
dasaka-ui  |     at NormalModule._initBuildHash (/app/node_modules/webpack/lib/NormalModule.js:417:16)
dasaka-ui  |     at handleParseError (/app/node_modules/webpack/lib/NormalModule.js:471:10)
dasaka-ui  |     at /app/node_modules/webpack/lib/NormalModule.js:503:5
dasaka-ui  |     at /app/node_modules/webpack/lib/NormalModule.js:358:12
dasaka-ui  |     at /app/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:373:3
dasaka-ui  |     at iterateNormalLoaders (/app/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
dasaka-ui  |     at Array.<anonymous> (/app/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
dasaka-ui  |     at Storage.finished (/app/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
dasaka-ui  |     at /app/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
dasaka-ui  |     at /app/node_modules/graceful-fs/graceful-fs.js:123:16
dasaka-ui  |     at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
dasaka-ui  |   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
dasaka-ui  |   library: 'digital envelope routines',
dasaka-ui  |   reason: 'unsupported',
dasaka-ui  |   code: 'ERR_OSSL_EVP_UNSUPPORTED'
dasaka-ui  | }
dasaka-ui  | 
dasaka-ui  | Node.js v18.15.0
dasaka-ui exited with code 1

**Comment by danikishin** [comment]
**Issue Solved**

The solution involved downgrading Node.js to an earlier version and using Docker to run the application. Here are the steps I followed:

- Updated the Dockerfile to use Node.js 14 LTS and included the HOST environment variable:
```
# Use Node.js 14 LTS image as the base image
FROM node:14

# ... existing Dockerfile content ...

# Set the environment variable for the host
ENV HOST=0.0.0.0

# ... existing Dockerfile content ...
```
- Rebuilt and restarted the Docker container


After doing this, I noticed that the application was running at http://172.24.0.2:3000/ inside the container. However, this URL didn't work in my browser. So, I ran ifconfig to find my local IP address, which was 192.168.0.15. Finally, I was able to access the application at http://192.168.0.15:3000.
